# Generated by Django 6.1 on 2026-08-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_personalinformation_rename_github_link_project_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('content', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='personalinformation',
            old_name='summary',
            new_name='bio',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='address',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='middle_name',
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='full_name',
            field=models.CharField(default='Default Name', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
